@baseURL=http://127.0.0.1:4000
###
# @name health
GET {{baseURL}}/health


###
# @name ping
GET {{baseURL}}/ping


###
# @name authRegister
POST {{baseURL}}/api/auth/register
Content-Type: "application/json"

{
    "email": "rodrigopmatias@gmail.com",
    "firstName": "Rodrigo",
    "lastName": "Matias",
    "password": "secr3t",
    "confirmPassword": "secr3t"
}


###
# @name authAuthenticate
POST {{baseURL}}/api/auth/authenticate
Content-Type: "application/json"

{
    "email": "rodrigopmatias@gmail.com",
    "password": "secr3t"
}


###
# @name authMe
GET {{baseURL}}/api/auth/me
Authorization: Bearer {{authAuthenticate.response.body.token}}